//! User-Controlled Deployment Workflow
//!
//! This module implements a user-centric deployment flow where:
//! - Users see ALL backtest results (no gatekeeping)
//! - Users decide whether to deploy (their money, their choice)
//! - Platform provides advisory warnings (informational, not blocking)
//! - Platform enforces hard safety limits (non-negotiable)
//! - High-capital deployments require admin review
//!
//! ## Philosophy
//!
//! The platform's role is to:
//! 1. Provide accurate metrics and analysis
//! 2. Warn users of potential risks (advisory)
//! 3. Enforce account-level safety rails (hard limits)
//! 4. Maintain audit trail for compliance
//!
//! The platform does NOT:
//! - Decide what Sharpe ratio is "good enough"
//! - Block strategies based on arbitrary thresholds
//! - Override user decisions about their own capital

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use uuid::Uuid;

// ============================================================================
// DEPLOYMENT REQUEST (User-Initiated)
// ============================================================================

/// A deployment request initiated by the user after reviewing backtest results
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DeploymentRequest {
    /// Unique identifier for this deployment request
    pub request_id: Uuid,
    /// User who initiated the deployment
    pub user_id: Uuid,
    /// Strategy identifier
    pub strategy_id: String,
    /// Strategy name
    pub strategy_name: String,
    /// Trading pair
    pub symbol: String,
    /// Exchange to deploy on
    pub exchange: String,
    /// Backtest performance metrics (ALL of them, unfiltered)
    pub backtest_metrics: BacktestMetrics,
    /// User's chosen risk configuration
    pub user_risk_config: UserRiskConfig,
    /// Advisory warnings generated by platform (informational only)
    pub advisory_warnings: Vec<AdvisoryWarning>,
    /// Risk acknowledgments signed by user
    pub risk_acknowledgments: Vec<RiskAcknowledgment>,
    /// Current status of the deployment
    pub status: DeploymentStatus,
    /// Platform's hard limit validation result
    pub platform_validation: PlatformValidation,
    /// Timestamps
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
}

/// All backtest metrics - shown to user without filtering
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BacktestMetrics {
    // Core performance
    pub sharpe_ratio: f64,
    pub sortino_ratio: f64,
    pub calmar_ratio: f64,
    pub profit_factor: f64,
    pub win_rate: f64,
    pub total_return_pct: f64,
    pub annualized_return_pct: f64,
    
    // Risk metrics
    pub max_drawdown_pct: f64,
    pub avg_drawdown_pct: f64,
    pub max_drawdown_duration_days: u32,
    pub volatility_annualized: f64,
    pub var_95: f64,  // Value at Risk 95%
    pub cvar_95: f64, // Conditional VaR 95%
    
    // Trade statistics
    pub total_trades: u64,
    pub avg_trade_return_pct: f64,
    pub avg_winning_trade_pct: f64,
    pub avg_losing_trade_pct: f64,
    pub largest_win_pct: f64,
    pub largest_loss_pct: f64,
    pub avg_trade_duration_hours: f64,
    
    // Walk-forward specific
    pub out_of_sample_sharpe: f64,
    pub parameter_stability_score: f64,
    pub profitable_windows: u32,
    pub total_windows: u32,
    
    // Monte Carlo results
    pub monte_carlo_median_return: f64,
    pub monte_carlo_5th_percentile: f64,
    pub monte_carlo_95th_percentile: f64,
    pub monte_carlo_probability_of_profit: f64,
    
    // Backtest period
    pub backtest_start: DateTime<Utc>,
    pub backtest_end: DateTime<Utc>,
    pub total_days: u32,
}

// ============================================================================
// USER RISK CONFIGURATION (User's Choice)
// ============================================================================

/// Risk configuration chosen by the user
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UserRiskConfig {
    /// Maximum position size as percentage of account
    pub max_position_pct: f64,
    /// User's daily loss limit (absolute value in USD)
    pub daily_loss_limit_usd: f64,
    /// User's per-trade stop loss percentage
    pub stop_loss_pct: f64,
    /// Optional take profit percentage
    pub take_profit_pct: Option<f64>,
    /// Capital allocated to this strategy (USD)
    pub allocated_capital_usd: f64,
    /// Leverage multiplier requested for this deployment. `1.0` = no leverage.
    #[serde(default = "default_user_leverage")]
    pub leverage: f64,
}

fn default_user_leverage() -> f64 { 1.0 }

impl Default for UserRiskConfig {
    fn default() -> Self {
        Self {
            max_position_pct: 0.05,      // 5% default
            daily_loss_limit_usd: 500.0, // $500 default
            stop_loss_pct: 0.02,         // 2% default
            take_profit_pct: None,
            allocated_capital_usd: 10000.0, // $10K default
            leverage: default_user_leverage(),
        }
    }
}

// ============================================================================
// ADVISORY WARNINGS (Informational, Not Blocking)
// ============================================================================

/// Advisory warning shown to user - informational only, does not block deployment
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AdvisoryWarning {
    /// Warning severity (for UI coloring)
    pub severity: WarningSeverity,
    /// Warning category
    pub category: WarningCategory,
    /// Human-readable warning message
    pub message: String,
    /// The metric that triggered this warning
    pub metric_name: String,
    /// Actual value of the metric
    pub actual_value: f64,
    /// Typical/reference value (for comparison)
    pub reference_value: f64,
    /// Additional context or suggestions
    pub context: Option<String>,
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq, Hash)]
pub enum WarningSeverity {
    /// Informational - just FYI
    Info,
    /// Caution - worth considering
    Caution,
    /// Warning - significant concern
    Warning,
    /// Critical - high risk indicator
    Critical,
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq)]
pub enum WarningCategory {
    Performance,
    Risk,
    StatisticalSignificance,
    MarketConditions,
    ParameterStability,
}

/// Generate advisory warnings based on backtest metrics
/// These are INFORMATIONAL ONLY - they do NOT block deployment
pub fn generate_advisory_warnings(metrics: &BacktestMetrics) -> Vec<AdvisoryWarning> {
    let mut warnings = Vec::new();
    
    // Sharpe ratio advisory
    if metrics.sharpe_ratio < 0.5 {
        warnings.push(AdvisoryWarning {
            severity: WarningSeverity::Warning,
            category: WarningCategory::Performance,
            message: "Sharpe ratio is below 0.5, indicating poor risk-adjusted returns".to_string(),
            metric_name: "sharpe_ratio".to_string(),
            actual_value: metrics.sharpe_ratio,
            reference_value: 1.0,
            context: Some("Sharpe > 1.0 is typically considered acceptable, > 2.0 is good".to_string()),
        });
    } else if metrics.sharpe_ratio < 1.0 {
        warnings.push(AdvisoryWarning {
            severity: WarningSeverity::Caution,
            category: WarningCategory::Performance,
            message: "Sharpe ratio is below 1.0".to_string(),
            metric_name: "sharpe_ratio".to_string(),
            actual_value: metrics.sharpe_ratio,
            reference_value: 1.0,
            context: Some("Many institutional traders require Sharpe > 1.0".to_string()),
        });
    }
    
    // Drawdown advisory
    if metrics.max_drawdown_pct > 0.30 {
        warnings.push(AdvisoryWarning {
            severity: WarningSeverity::Critical,
            category: WarningCategory::Risk,
            message: format!("Maximum drawdown of {:.1}% is very high", metrics.max_drawdown_pct * 100.0),
            metric_name: "max_drawdown_pct".to_string(),
            actual_value: metrics.max_drawdown_pct,
            reference_value: 0.15,
            context: Some("You could lose more than 30% of your position at some point".to_string()),
        });
    } else if metrics.max_drawdown_pct > 0.20 {
        warnings.push(AdvisoryWarning {
            severity: WarningSeverity::Warning,
            category: WarningCategory::Risk,
            message: format!("Maximum drawdown of {:.1}% is elevated", metrics.max_drawdown_pct * 100.0),
            metric_name: "max_drawdown_pct".to_string(),
            actual_value: metrics.max_drawdown_pct,
            reference_value: 0.15,
            context: Some("Consider if you can tolerate this level of drawdown".to_string()),
        });
    }
    
    // Statistical significance advisory
    if metrics.total_trades < 30 {
        warnings.push(AdvisoryWarning {
            severity: WarningSeverity::Critical,
            category: WarningCategory::StatisticalSignificance,
            message: format!("Only {} trades in backtest - results may not be statistically significant", metrics.total_trades),
            metric_name: "total_trades".to_string(),
            actual_value: metrics.total_trades as f64,
            reference_value: 100.0,
            context: Some("Recommend at least 100 trades for statistical confidence".to_string()),
        });
    } else if metrics.total_trades < 100 {
        warnings.push(AdvisoryWarning {
            severity: WarningSeverity::Caution,
            category: WarningCategory::StatisticalSignificance,
            message: format!("{} trades may have limited statistical significance", metrics.total_trades),
            metric_name: "total_trades".to_string(),
            actual_value: metrics.total_trades as f64,
            reference_value: 100.0,
            context: None,
        });
    }
    
    // Win rate advisory (informational - some strategies win small and lose big, others opposite)
    if metrics.win_rate < 0.40 {
        warnings.push(AdvisoryWarning {
            severity: WarningSeverity::Info,
            category: WarningCategory::Performance,
            message: format!("Win rate of {:.1}% is below 50%", metrics.win_rate * 100.0),
            metric_name: "win_rate".to_string(),
            actual_value: metrics.win_rate,
            reference_value: 0.50,
            context: Some("This can be fine if average wins are larger than average losses (check profit factor)".to_string()),
        });
    }
    
    // Parameter stability advisory
    if metrics.parameter_stability_score < 0.6 {
        warnings.push(AdvisoryWarning {
            severity: WarningSeverity::Warning,
            category: WarningCategory::ParameterStability,
            message: "Parameters showed instability across walk-forward windows".to_string(),
            metric_name: "parameter_stability_score".to_string(),
            actual_value: metrics.parameter_stability_score,
            reference_value: 0.8,
            context: Some("Strategy may be overfit to specific market conditions".to_string()),
        });
    }
    
    // Out-of-sample vs in-sample comparison
    if metrics.out_of_sample_sharpe < metrics.sharpe_ratio * 0.5 {
        warnings.push(AdvisoryWarning {
            severity: WarningSeverity::Warning,
            category: WarningCategory::ParameterStability,
            message: "Out-of-sample performance significantly lower than in-sample".to_string(),
            metric_name: "out_of_sample_sharpe".to_string(),
            actual_value: metrics.out_of_sample_sharpe,
            reference_value: metrics.sharpe_ratio,
            context: Some("This may indicate overfitting to historical data".to_string()),
        });
    }
    
    // Monte Carlo probability warning
    if metrics.monte_carlo_probability_of_profit < 0.6 {
        warnings.push(AdvisoryWarning {
            severity: WarningSeverity::Warning,
            category: WarningCategory::Risk,
            message: format!("Monte Carlo shows {:.1}% probability of profit", metrics.monte_carlo_probability_of_profit * 100.0),
            metric_name: "monte_carlo_probability_of_profit".to_string(),
            actual_value: metrics.monte_carlo_probability_of_profit,
            reference_value: 0.70,
            context: Some("Across randomized scenarios, profitability is uncertain".to_string()),
        });
    }
    
    // Backtest period advisory
    if metrics.total_days < 180 {
        warnings.push(AdvisoryWarning {
            severity: WarningSeverity::Caution,
            category: WarningCategory::StatisticalSignificance,
            message: format!("Backtest period of {} days is relatively short", metrics.total_days),
            metric_name: "total_days".to_string(),
            actual_value: metrics.total_days as f64,
            reference_value: 365.0,
            context: Some("Longer backtests capture more market conditions".to_string()),
        });
    }
    
    warnings
}

// ============================================================================
// RISK ACKNOWLEDGMENT (User Must Sign)
// ============================================================================

/// Risk acknowledgment that user must explicitly accept
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RiskAcknowledgment {
    /// Type of risk being acknowledged
    pub risk_type: RiskType,
    /// The specific statement user is acknowledging
    pub statement: String,
    /// Whether user has acknowledged this risk
    pub acknowledged: bool,
    /// Timestamp when acknowledged
    pub acknowledged_at: Option<DateTime<Utc>>,
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq)]
pub enum RiskType {
    /// General trading risk
    TradingRisk,
    /// Specific drawdown risk
    DrawdownRisk,
    /// Capital loss risk
    CapitalLossRisk,
    /// Past performance disclaimer
    PastPerformance,
    /// Strategy-specific risk
    StrategySpecific,
}

/// Generate required risk acknowledgments based on metrics and config
pub fn generate_required_acknowledgments(
    metrics: &BacktestMetrics,
    user_config: &UserRiskConfig,
) -> Vec<RiskAcknowledgment> {
    let mut acks = Vec::new();
    
    // Always required: General trading risk
    acks.push(RiskAcknowledgment {
        risk_type: RiskType::TradingRisk,
        statement: "I understand that algorithmic trading involves significant risk and I may lose money.".to_string(),
        acknowledged: false,
        acknowledged_at: None,
    });
    
    // Always required: Past performance disclaimer
    acks.push(RiskAcknowledgment {
        risk_type: RiskType::PastPerformance,
        statement: "I understand that past backtest performance does not guarantee future results.".to_string(),
        acknowledged: false,
        acknowledged_at: None,
    });
    
    // Specific drawdown acknowledgment if high
    if metrics.max_drawdown_pct > 0.15 {
        acks.push(RiskAcknowledgment {
            risk_type: RiskType::DrawdownRisk,
            statement: format!(
                "I understand this strategy showed a maximum drawdown of {:.1}% in backtesting, and I may experience similar or larger drawdowns in live trading.",
                metrics.max_drawdown_pct * 100.0
            ),
            acknowledged: false,
            acknowledged_at: None,
        });
    }
    
    // Capital loss acknowledgment for significant allocations
    if user_config.allocated_capital_usd > 5000.0 {
        acks.push(RiskAcknowledgment {
            risk_type: RiskType::CapitalLossRisk,
            statement: format!(
                "I am allocating ${:.2} to this strategy and I can afford to lose this amount.",
                user_config.allocated_capital_usd
            ),
            acknowledged: false,
            acknowledged_at: None,
        });
    }
    
    // Strategy-specific risks
    if metrics.win_rate < 0.40 && metrics.profit_factor > 1.5 {
        acks.push(RiskAcknowledgment {
            risk_type: RiskType::StrategySpecific,
            statement: "I understand this strategy has a low win rate and relies on large winning trades to be profitable. I may experience many consecutive losses.".to_string(),
            acknowledged: false,
            acknowledged_at: None,
        });
    }
    
    if metrics.parameter_stability_score < 0.7 {
        acks.push(RiskAcknowledgment {
            risk_type: RiskType::StrategySpecific,
            statement: "I understand this strategy showed parameter instability in walk-forward testing, which may indicate sensitivity to market conditions.".to_string(),
            acknowledged: false,
            acknowledged_at: None,
        });
    }
    
    acks
}

// ============================================================================
// PLATFORM HARD LIMITS (Non-Negotiable)
// ============================================================================

/// Platform-enforced limits that cannot be overridden by users
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PlatformLimits {
    /// Maximum position size as percentage of account (platform cap)
    pub max_position_pct_cap: f64,
    /// Maximum daily loss as percentage of account
    pub max_daily_loss_pct_cap: f64,
    /// Minimum required backtest period (days)
    pub min_backtest_days: u32,
    /// Maximum leverage allowed
    pub max_leverage: f64,
    /// Capital threshold requiring admin review (USD)
    pub admin_review_threshold_usd: f64,
    /// Capital threshold requiring multi-sig approval (USD)
    pub multi_sig_threshold_usd: f64,
}

impl Default for PlatformLimits {
    fn default() -> Self {
        Self {
            max_position_pct_cap: 0.20,           // Max 20% of account in one position
            max_daily_loss_pct_cap: 0.10,         // Max 10% daily loss
            min_backtest_days: 30,                // At least 30 days of data
            max_leverage: 3.0,                    // Max 3x leverage
            admin_review_threshold_usd: 25_000.0, // Admin review for >$25K
            multi_sig_threshold_usd: 100_000.0,   // Multi-sig for >$100K
        }
    }
}

/// Result of platform validation
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PlatformValidation {
    /// Whether the deployment passes platform hard limits
    pub passes_hard_limits: bool,
    /// List of hard limit violations (if any)
    pub violations: Vec<HardLimitViolation>,
    /// Adjusted values (platform may cap user values)
    pub adjusted_config: Option<UserRiskConfig>,
    /// Required approval level based on capital
    pub required_approval: ApprovalRequirement,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct HardLimitViolation {
    pub limit_name: String,
    pub user_value: f64,
    pub platform_limit: f64,
    pub message: String,
    /// Whether this can be auto-adjusted or requires rejection
    pub auto_adjustable: bool,
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq)]
pub enum ApprovalRequirement {
    /// No admin approval needed
    None,
    /// Single admin must approve
    AdminReview,
    /// Multiple admins must approve
    MultiSigRequired,
}

/// Validate deployment request against platform hard limits
pub fn validate_platform_limits(
    user_config: &UserRiskConfig,
    metrics: &BacktestMetrics,
    limits: &PlatformLimits,
) -> PlatformValidation {
    let mut violations = Vec::new();
    let mut adjusted_config = user_config.clone();
    let mut needs_adjustment = false;
    
    // Check position size cap
    if user_config.max_position_pct > limits.max_position_pct_cap {
        violations.push(HardLimitViolation {
            limit_name: "max_position_pct".to_string(),
            user_value: user_config.max_position_pct,
            platform_limit: limits.max_position_pct_cap,
            message: format!(
                "Position size {:.1}% exceeds platform cap of {:.1}% - will be reduced",
                user_config.max_position_pct * 100.0,
                limits.max_position_pct_cap * 100.0
            ),
            auto_adjustable: true,
        });
        adjusted_config.max_position_pct = limits.max_position_pct_cap;
        needs_adjustment = true;
    }
    
    // Check daily loss as percentage of allocated capital
    let daily_loss_pct = user_config.daily_loss_limit_usd / user_config.allocated_capital_usd;
    if daily_loss_pct > limits.max_daily_loss_pct_cap {
        let max_daily_loss = user_config.allocated_capital_usd * limits.max_daily_loss_pct_cap;
        violations.push(HardLimitViolation {
            limit_name: "daily_loss_limit".to_string(),
            user_value: user_config.daily_loss_limit_usd,
            platform_limit: max_daily_loss,
            message: format!(
                "Daily loss limit ${:.2} exceeds {:.1}% of capital - will be reduced to ${:.2}",
                user_config.daily_loss_limit_usd,
                limits.max_daily_loss_pct_cap * 100.0,
                max_daily_loss
            ),
            auto_adjustable: true,
        });
        adjusted_config.daily_loss_limit_usd = max_daily_loss;
        needs_adjustment = true;
    }
    
    // Check leverage cap
    if user_config.leverage > limits.max_leverage {
        violations.push(HardLimitViolation {
            limit_name: "leverage".to_string(),
            user_value: user_config.leverage,
            platform_limit: limits.max_leverage,
            message: format!(
                "Leverage {:.1}x exceeds platform cap of {:.1}x - will be reduced",
                user_config.leverage, limits.max_leverage
            ),
            auto_adjustable: true,
        });
        adjusted_config.leverage = limits.max_leverage;
        needs_adjustment = true;
    }

    // Check minimum backtest period (non-adjustable - must reject)
    if metrics.total_days < limits.min_backtest_days {
        violations.push(HardLimitViolation {
            limit_name: "min_backtest_days".to_string(),
            user_value: metrics.total_days as f64,
            platform_limit: limits.min_backtest_days as f64,
            message: format!(
                "Backtest period of {} days is below minimum required {} days",
                metrics.total_days,
                limits.min_backtest_days
            ),
            auto_adjustable: false,
        });
    }
    
    // Determine if passes (only fails if non-adjustable violations exist)
    let passes = violations.iter().all(|v| v.auto_adjustable);
    
    // Determine approval requirement based on capital
    let required_approval = if user_config.allocated_capital_usd >= limits.multi_sig_threshold_usd {
        ApprovalRequirement::MultiSigRequired
    } else if user_config.allocated_capital_usd >= limits.admin_review_threshold_usd {
        ApprovalRequirement::AdminReview
    } else {
        ApprovalRequirement::None
    };
    
    PlatformValidation {
        passes_hard_limits: passes,
        violations,
        adjusted_config: if needs_adjustment { Some(adjusted_config) } else { None },
        required_approval,
    }
}

// ============================================================================
// DEPLOYMENT STATUS & WORKFLOW
// ============================================================================

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq)]
pub enum DeploymentStatus {
    /// User is reviewing backtest results
    PendingUserReview,
    /// Waiting for user to acknowledge risks
    PendingRiskAcknowledgment,
    /// Waiting for admin approval (high capital)
    PendingAdminApproval,
    /// Waiting for multi-sig approval (very high capital)
    PendingMultiSigApproval,
    /// Approved and ready to deploy
    Approved,
    /// Rejected by platform (hard limit violation)
    RejectedByPlatform,
    /// Rejected by admin
    RejectedByAdmin,
    /// Cancelled by user
    CancelledByUser,
    /// Successfully deployed to SignalEngine
    Deployed,
    /// Deployment failed (technical error)
    DeploymentFailed,
}

/// Admin approval record
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AdminApproval {
    pub admin_id: Uuid,
    pub admin_name: String,
    pub decision: AdminDecision,
    pub notes: Option<String>,
    pub decided_at: DateTime<Utc>,
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq)]
pub enum AdminDecision {
    Approved,
    Rejected,
    RequestMoreInfo,
}

// ============================================================================
// DEPLOYMENT REQUEST BUILDER
// ============================================================================

impl DeploymentRequest {
    /// Create a new deployment request from backtest results
    pub fn new(
        user_id: Uuid,
        strategy_id: String,
        strategy_name: String,
        symbol: String,
        exchange: String,
        metrics: BacktestMetrics,
        user_config: UserRiskConfig,
    ) -> Self {
        let advisory_warnings = generate_advisory_warnings(&metrics);
        let risk_acknowledgments = generate_required_acknowledgments(&metrics, &user_config);
        let platform_validation = validate_platform_limits(
            &user_config,
            &metrics,
            &PlatformLimits::default(),
        );
        
        let initial_status = if !platform_validation.passes_hard_limits {
            DeploymentStatus::RejectedByPlatform
        } else {
            DeploymentStatus::PendingUserReview
        };
        
        let now = Utc::now();
        
        Self {
            request_id: Uuid::new_v4(),
            user_id,
            strategy_id,
            strategy_name,
            symbol,
            exchange,
            backtest_metrics: metrics,
            user_risk_config: user_config,
            advisory_warnings,
            risk_acknowledgments,
            status: initial_status,
            platform_validation,
            created_at: now,
            updated_at: now,
        }
    }
    
    /// Check if user has acknowledged all required risks
    pub fn all_risks_acknowledged(&self) -> bool {
        self.risk_acknowledgments.iter().all(|ack| ack.acknowledged)
    }
    
    /// Acknowledge a specific risk
    pub fn acknowledge_risk(&mut self, risk_type: RiskType) -> bool {
        if let Some(ack) = self.risk_acknowledgments.iter_mut().find(|a| a.risk_type == risk_type) {
            ack.acknowledged = true;
            ack.acknowledged_at = Some(Utc::now());
            self.updated_at = Utc::now();
            
            // Update status if all acknowledged
            if self.status == DeploymentStatus::PendingRiskAcknowledgment && self.all_risks_acknowledged() {
                self.status = match self.platform_validation.required_approval {
                    ApprovalRequirement::None => DeploymentStatus::Approved,
                    ApprovalRequirement::AdminReview => DeploymentStatus::PendingAdminApproval,
                    ApprovalRequirement::MultiSigRequired => DeploymentStatus::PendingMultiSigApproval,
                };
            }
            true
        } else {
            false
        }
    }
    
    /// User confirms they want to proceed (moves to risk acknowledgment)
    pub fn user_confirms_review(&mut self) {
        if self.status == DeploymentStatus::PendingUserReview {
            self.status = DeploymentStatus::PendingRiskAcknowledgment;
            self.updated_at = Utc::now();
        }
    }
    
    /// User cancels deployment
    pub fn cancel(&mut self) {
        self.status = DeploymentStatus::CancelledByUser;
        self.updated_at = Utc::now();
    }
    
    /// Admin approves deployment
    pub fn admin_approve(&mut self, _admin_id: Uuid, _admin_name: String, _notes: Option<String>) {
        if self.status == DeploymentStatus::PendingAdminApproval {
            self.status = DeploymentStatus::Approved;
            self.updated_at = Utc::now();
            // In production, store AdminApproval record
        }
    }
    
    /// Admin rejects deployment
    pub fn admin_reject(&mut self, _admin_id: Uuid, _admin_name: String, _reason: String) {
        if self.status == DeploymentStatus::PendingAdminApproval 
            || self.status == DeploymentStatus::PendingMultiSigApproval {
            self.status = DeploymentStatus::RejectedByAdmin;
            self.updated_at = Utc::now();
            // In production, store AdminApproval record with rejection reason
        }
    }
    
    /// Check if deployment is ready to go live
    pub fn is_ready_for_deployment(&self) -> bool {
        self.status == DeploymentStatus::Approved
    }
    
    /// Get count of warnings by severity
    pub fn warning_counts(&self) -> HashMap<WarningSeverity, usize> {
        let mut counts = HashMap::new();
        for warning in &self.advisory_warnings {
            *counts.entry(warning.severity).or_insert(0) += 1;
        }
        counts
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    
    fn sample_metrics() -> BacktestMetrics {
        BacktestMetrics {
            sharpe_ratio: 1.2,
            sortino_ratio: 1.5,
            calmar_ratio: 0.8,
            profit_factor: 1.4,
            win_rate: 0.55,
            total_return_pct: 0.25,
            annualized_return_pct: 0.30,
            max_drawdown_pct: 0.18,
            avg_drawdown_pct: 0.08,
            max_drawdown_duration_days: 14,
            volatility_annualized: 0.20,
            var_95: 0.03,
            cvar_95: 0.05,
            total_trades: 150,
            avg_trade_return_pct: 0.002,
            avg_winning_trade_pct: 0.015,
            avg_losing_trade_pct: -0.010,
            largest_win_pct: 0.08,
            largest_loss_pct: -0.05,
            avg_trade_duration_hours: 4.5,
            out_of_sample_sharpe: 1.0,
            parameter_stability_score: 0.85,
            profitable_windows: 4,
            total_windows: 5,
            monte_carlo_median_return: 0.22,
            monte_carlo_5th_percentile: 0.05,
            monte_carlo_95th_percentile: 0.45,
            monte_carlo_probability_of_profit: 0.78,
            backtest_start: Utc::now() - chrono::Duration::days(365),
            backtest_end: Utc::now(),
            total_days: 365,
        }
    }
    
    #[test]
    fn test_advisory_warnings_generated() {
        let mut metrics = sample_metrics();
        // Set drawdown to 25% to trigger warning (threshold is > 20%)
        metrics.max_drawdown_pct = 0.25;
        let warnings = generate_advisory_warnings(&metrics);
        
        // Should have drawdown warning (25% > 20% threshold)
        assert!(warnings.iter().any(|w| w.metric_name == "max_drawdown_pct"));
    }
    
    #[test]
    fn test_platform_validation_passes() {
        let metrics = sample_metrics();
        let config = UserRiskConfig::default();
        let limits = PlatformLimits::default();
        
        let validation = validate_platform_limits(&config, &metrics, &limits);
        
        assert!(validation.passes_hard_limits);
        assert_eq!(validation.required_approval, ApprovalRequirement::None);
    }
    
    #[test]
    fn test_high_capital_requires_admin() {
        let metrics = sample_metrics();
        let mut config = UserRiskConfig::default();
        config.allocated_capital_usd = 50_000.0; // Above admin threshold
        let limits = PlatformLimits::default();
        
        let validation = validate_platform_limits(&config, &metrics, &limits);
        
        assert_eq!(validation.required_approval, ApprovalRequirement::AdminReview);
    }
    
    #[test]
    fn test_very_high_capital_requires_multisig() {
        let metrics = sample_metrics();
        let mut config = UserRiskConfig::default();
        config.allocated_capital_usd = 150_000.0; // Above multi-sig threshold
        let limits = PlatformLimits::default();
        
        let validation = validate_platform_limits(&config, &metrics, &limits);
        
        assert_eq!(validation.required_approval, ApprovalRequirement::MultiSigRequired);
    }
    
    #[test]
    fn test_position_size_auto_adjusted() {
        let metrics = sample_metrics();
        let mut config = UserRiskConfig::default();
        config.max_position_pct = 0.50; // 50% - above platform cap
        let limits = PlatformLimits::default();
        
        let validation = validate_platform_limits(&config, &metrics, &limits);
        
        assert!(validation.passes_hard_limits); // Still passes (auto-adjusted)
        assert!(validation.adjusted_config.is_some());
        assert_eq!(validation.adjusted_config.unwrap().max_position_pct, 0.20);
    }

    #[test]
    fn test_leverage_auto_adjusted_to_platform_cap() {
        let metrics = sample_metrics();
        let mut config = UserRiskConfig::default();
        config.leverage = 10.0; // above the default 3.0x platform cap
        let limits = PlatformLimits::default();

        let validation = validate_platform_limits(&config, &metrics, &limits);

        assert!(validation.passes_hard_limits); // Still passes (auto-adjusted)
        assert!(validation.adjusted_config.is_some());
        assert_eq!(validation.adjusted_config.unwrap().leverage, 3.0);
        assert!(validation.violations.iter().any(|v| v.limit_name == "leverage"));
    }

    #[test]
    fn test_leverage_within_cap_not_flagged() {
        let metrics = sample_metrics();
        let mut config = UserRiskConfig::default();
        config.leverage = 2.0; // within the default 3.0x cap
        let limits = PlatformLimits::default();

        let validation = validate_platform_limits(&config, &metrics, &limits);

        assert!(!validation.violations.iter().any(|v| v.limit_name == "leverage"));
    }

    #[test]
    fn test_insufficient_backtest_rejected() {
        let mut metrics = sample_metrics();
        metrics.total_days = 15; // Below minimum
        let config = UserRiskConfig::default();
        let limits = PlatformLimits::default();
        
        let validation = validate_platform_limits(&config, &metrics, &limits);
        
        assert!(!validation.passes_hard_limits); // Fails - not auto-adjustable
    }
    
    #[test]
    fn test_deployment_request_workflow() {
        let metrics = sample_metrics();
        let config = UserRiskConfig::default();
        
        let mut request = DeploymentRequest::new(
            Uuid::new_v4(),
            "test-strategy".to_string(),
            "Test Strategy".to_string(),
            "BTCUSD".to_string(),
            "kraken".to_string(),
            metrics,
            config,
        );
        
        // Initial status
        assert_eq!(request.status, DeploymentStatus::PendingUserReview);
        
        // User confirms review
        request.user_confirms_review();
        assert_eq!(request.status, DeploymentStatus::PendingRiskAcknowledgment);
        
        // Acknowledge all risks
        for ack in request.risk_acknowledgments.clone() {
            request.acknowledge_risk(ack.risk_type);
        }
        
        // Should now be approved (low capital, no admin needed)
        assert_eq!(request.status, DeploymentStatus::Approved);
        assert!(request.is_ready_for_deployment());
    }
}
