//! Trading signal definitions and utilities

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::sync::Arc;

pub use derivatives::{DerivativeMetadata, Greeks, InstrumentKind};

/// A trading signal generated by a strategy
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Signal {
    pub id: Arc<str>,
    pub timestamp: DateTime<Utc>,
    pub signal_type: SignalType,
    pub strength: SignalStrength,
    pub price: Option<f64>,
    pub quantity: Option<f64>,
    pub reason: SignalReason,
    pub metadata: HashMap<String, SignalMetadata>,
    /// Fast numeric metadata for Python strategies.
    /// Allows strategies to attach arbitrary f64 values (e.g. confidence,
    /// urgency, implied_vol) without going through the SignalMetadata enum.
    #[serde(default)]
    pub numeric_metadata: HashMap<String, f64>,
    /// When true, the signal requests a limit/maker fill (passive, sits on book).
    /// When false (default), the signal requests a taker fill (market/IOC).
    /// The engine routes each signal individually to the correct fill model
    /// and fee schedule regardless of which base class the strategy uses.
    #[serde(default)]
    pub is_limit: bool,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub enum SignalType {
    Buy,
    Sell,
    Hold,
    Close,
    ScaleIn,
    ScaleOut,
    StopLoss,
    TakeProfit,
    /// Two-sided quote for market making: simultaneously quote bid and ask.
    /// Used by Python custom MM strategies to express both sides of the market.
    TwoSidedQuote {
        bid_price: f64,
        ask_price: f64,
        bid_size: f64,
        ask_size: f64,
    },
    /// Cancel all outstanding quotes (used by MM strategies during risk events).
    CancelQuotes,
    /// Multi-asset signal: target a specific symbol different from the current context.
    /// Allows Python strategies to emit signals for multiple instruments.
    CrossAsset {
        target_symbol: String,
        target_exchange: String,
        action: Box<SignalType>,
    },
    Custom(String),

    // ── Derivatives ──────────────────────────────────────────────────────

    /// Buy (go long) an option contract at the given premium.
    BuyOption {
        instrument: DerivativeMetadata,
        /// Limit premium per contract (quotes currency). `None` = market.
        premium: Option<f64>,
    },
    /// Sell (write) an option contract at the given premium.
    SellOption {
        instrument: DerivativeMetadata,
        /// Minimum acceptable premium. `None` = market.
        premium: Option<f64>,
    },
    /// Buy (go long) a futures contract.
    BuyFuture {
        instrument: DerivativeMetadata,
    },
    /// Sell (go short) a futures / perpetual contract.
    SellFuture {
        instrument: DerivativeMetadata,
    },
    /// Multi-leg spread order (straddle, spread, condor, butterfly, …).
    /// All legs are executed atomically: all-or-nothing.
    OptionSpread {
        legs: Vec<SpreadLeg>,
    },
    /// Roll an existing position from an expiring contract to the next one.
    RollContract {
        from_symbol: String,
        to_symbol: String,
        from_instrument: DerivativeMetadata,
        to_instrument: DerivativeMetadata,
    },
    /// Exercise an in-the-money option prior to (or at) expiry.
    ExerciseOption {
        instrument: DerivativeMetadata,
    },
    /// Delta-hedge: adjust the hedge position to reach a target portfolio delta.
    HedgeDelta {
        /// Desired net portfolio delta after the hedge.
        target_delta: f64,
        /// Current portfolio delta (before the hedge).
        current_delta: f64,
        /// Symbol used to delta-hedge (typically the underlying spot or perpetual).
        hedge_instrument: String,
    },

    // ── Liquidity Provision ─────────────────────────────────────────────

    /// Add liquidity to a DEX pool.
    AddLiquidity {
        pool_id: String,
        pool_type: String,
        amount_a: f64,
        amount_b: f64,
        tick_lower: Option<i32>,
        tick_upper: Option<i32>,
    },
    /// Remove liquidity from a DEX pool position.
    RemoveLiquidity {
        pool_id: String,
        /// Fraction to remove (1.0 = full withdrawal).
        fraction: f64,
    },
    /// Rebalance a concentrated liquidity position to a new tick range.
    Rebalance {
        pool_id: String,
        new_tick_lower: i32,
        new_tick_upper: i32,
    },
}

/// A single leg in a multi-leg derivative spread.
///
/// `ratio` is signed: positive = long, negative = short.  
/// Example: a long straddle has two legs with ratio +1 each (one call, one put).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct SpreadLeg {
    /// The action for this leg (e.g. `BuyOption { .. }` or `SellOption { .. }`).
    pub signal_type: SignalType,
    /// Signed ratio: +1 = long 1 contract, -2 = short 2 contracts.
    pub ratio: i32,
    /// Optional limit price for this leg.
    pub limit_price: Option<f64>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub enum SignalStrength {
    Weak,
    Medium,
    Strong,
    Custom(f64),
}


#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub enum SignalReason {
    TechnicalAnalysis(String),
    FundamentalAnalysis(String),
    RiskManagement(String),
    RegimeChange(String),
    VolumeAnalysis(String),
    PriceAction(String),
    MeanReversion(String),
    Momentum(String),
    Arbitrage(String),
    Custom(String, String),
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub enum SignalMetadata {
    Number(f64),
    Text(String),
    Boolean(bool),
    Timestamp(DateTime<Utc>),
    Price(f64),
    Percentage(f64),
}

impl SignalReason {
    pub fn description(&self) -> String {
        match self {
            SignalReason::TechnicalAnalysis(desc) => format!("Technical Analysis: {}", desc),
            SignalReason::FundamentalAnalysis(desc) => format!("Fundamental Analysis: {}", desc),
            SignalReason::RiskManagement(desc) => format!("Risk Management: {}", desc),
            SignalReason::RegimeChange(desc) => format!("Regime Change: {}", desc),
            SignalReason::VolumeAnalysis(desc) => format!("Volume Analysis: {}", desc),
            SignalReason::PriceAction(desc) => format!("Price Action: {}", desc),
            SignalReason::MeanReversion(desc) => format!("Mean Reversion: {}", desc),
            SignalReason::Momentum(desc) => format!("Momentum: {}", desc),
            SignalReason::Arbitrage(desc) => format!("Arbitrage: {}", desc),
            SignalReason::Custom(category, desc) => format!("{}: {}", category, desc),
        }
    }
}

impl SignalMetadata {
    pub fn as_float(&self) -> Option<f64> {
        match self {
            SignalMetadata::Number(n) => Some(*n),
            SignalMetadata::Percentage(p) => Some(*p),
            SignalMetadata::Boolean(b) => Some(if *b { 1.0 } else { 0.0 }),
            SignalMetadata::Price(p) => Some(*p),
            _ => None,
        }
    }
    pub fn as_string(&self) -> String {
        match self {
            SignalMetadata::Number(n) => n.to_string(),
            SignalMetadata::Text(s) => s.clone(),
            SignalMetadata::Boolean(b) => b.to_string(),
            SignalMetadata::Timestamp(ts) => ts.to_rfc3339(),
            SignalMetadata::Price(p) => format!("{}", p),
            SignalMetadata::Percentage(p) => format!("{:.2}%", p * 100.0),
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SignalValidation {
    pub is_valid: bool,
    pub errors: Vec<String>,
    pub warnings: Vec<String>,
}

impl Signal {
    pub fn new(
        id: impl Into<Arc<str>>,
        signal_type: SignalType,
        strength: SignalStrength,
        reason: SignalReason,
    ) -> Self {
        Signal {
            id: id.into(),
            timestamp: Utc::now(),
            signal_type,
            strength,
            price: None,
            quantity: None,
            reason,
            metadata: HashMap::new(),
            numeric_metadata: HashMap::new(),
            is_limit: false,
        }
    }

    pub fn buy(id: impl Into<Arc<str>>, strength: SignalStrength, reason: SignalReason) -> Self {
        Self::new(id, SignalType::Buy, strength, reason)
    }
    pub fn sell(id: impl Into<Arc<str>>, strength: SignalStrength, reason: SignalReason) -> Self {
        Self::new(id, SignalType::Sell, strength, reason)
    }
    pub fn hold(id: impl Into<Arc<str>>, reason: SignalReason) -> Self {
        Self::new(id, SignalType::Hold, SignalStrength::Medium, reason)
    }
    pub fn close(id: impl Into<Arc<str>>, strength: SignalStrength, reason: SignalReason) -> Self {
        Self::new(id, SignalType::Close, strength, reason)
    }
    /// Create a two-sided quote signal (for market making strategies).
    pub fn two_sided_quote(
        id: impl Into<Arc<str>>,
        bid_price: f64,
        ask_price: f64,
        bid_size: f64,
        ask_size: f64,
        strength: SignalStrength,
        reason: SignalReason,
    ) -> Self {
        Self::new(
            id,
            SignalType::TwoSidedQuote { bid_price, ask_price, bid_size, ask_size },
            strength,
            reason,
        )
    }
    /// Create a cancel-all-quotes signal.
    pub fn cancel_quotes(id: impl Into<Arc<str>>, reason: SignalReason) -> Self {
        Self::new(id, SignalType::CancelQuotes, SignalStrength::Strong, reason)
    }
    pub fn with_price(mut self, price: f64) -> Self {
        self.price = Some(price);
        self
    }
    pub fn with_quantity(mut self, quantity: f64) -> Self {
        self.quantity = Some(quantity);
        self
    }
    pub fn with_metadata(mut self, key: String, value: SignalMetadata) -> Self {
        self.metadata.insert(key, value);
        self
    }
    pub fn with_numeric(mut self, key: impl Into<String>, value: f64) -> Self {
        self.numeric_metadata.insert(key.into(), value);
        self
    }
    /// Mark this signal as a limit/maker order (passive, sits on book).
    /// Default is taker (market/IOC). Both BaseStrategy and MarketMakingStrategy
    /// can emit either taker or maker signals — the base class determines order
    /// lifecycle (fire-and-forget vs continuous quoting), not fill type.
    pub fn with_limit(mut self, is_limit: bool) -> Self {
        self.is_limit = is_limit;
        self
    }
    pub fn with_timestamp(mut self, timestamp: DateTime<Utc>) -> Self {
        self.timestamp = timestamp;
        self
    }
    pub fn is_entry_signal(&self) -> bool {
        matches!(
            self.signal_type,
            SignalType::Buy
                | SignalType::Sell
                | SignalType::TwoSidedQuote { .. }
                | SignalType::BuyOption { .. }
                | SignalType::SellOption { .. }
                | SignalType::BuyFuture { .. }
                | SignalType::SellFuture { .. }
                | SignalType::OptionSpread { .. }
                | SignalType::HedgeDelta { .. }
        )
    }
    pub fn is_exit_signal(&self) -> bool {
        matches!(
            self.signal_type,
            SignalType::Close
                | SignalType::StopLoss
                | SignalType::TakeProfit
                | SignalType::CancelQuotes
                | SignalType::ExerciseOption { .. }
                | SignalType::RollContract { .. }
        )
    }
    pub fn is_scaling_signal(&self) -> bool {
        matches!(self.signal_type, SignalType::ScaleIn | SignalType::ScaleOut)
    }
    pub fn strength_value(&self) -> f64 {
        match self.strength {
            SignalStrength::Weak => 0.33,
            SignalStrength::Medium => 0.66,
            SignalStrength::Strong => 1.0,
            SignalStrength::Custom(val) => val,
        }
    }
    pub fn validate(&self) -> SignalValidation {
        let mut errors = Vec::new();
        let mut warnings = Vec::new();
        if self.id.is_empty() {
            errors.push("Signal ID cannot be empty".to_string());
        }
        if self.is_entry_signal() {
            if self.price.is_none() {
                warnings.push("Entry signal without suggested price".to_string());
            }
            if self.quantity.is_none() {
                warnings.push("Entry signal without suggested quantity".to_string());
            }
        }
        if let Some(price) = self.price {
            if price <= 0.0 {
                errors.push("Signal price must be positive".to_string());
            }
        }
        if let Some(quantity) = self.quantity {
            if quantity <= 0.0 {
                errors.push("Signal quantity must be positive".to_string());
            }
        }
        // Derivative-specific validation
        match &self.signal_type {
            SignalType::OptionSpread { legs } => {
                if legs.is_empty() {
                    errors.push("OptionSpread must have at least one leg".to_string());
                }
                if legs.iter().all(|l| l.ratio == 0) {
                    errors.push("OptionSpread legs must have non-zero ratios".to_string());
                }
            }
            SignalType::HedgeDelta { target_delta, current_delta, hedge_instrument } => {
                if hedge_instrument.is_empty() {
                    errors.push("HedgeDelta hedge_instrument cannot be empty".to_string());
                }
                if (target_delta - current_delta).abs() < 1e-9 {
                    warnings.push("HedgeDelta: target_delta equals current_delta — no action needed".to_string());
                }
            }
            SignalType::RollContract { from_symbol, to_symbol, .. } => {
                if from_symbol == to_symbol {
                    errors.push("RollContract from_symbol and to_symbol must differ".to_string());
                }
            }
            _ => {}
        }
        let now = Utc::now();
        if self.timestamp > now + chrono::Duration::seconds(10) {
            warnings.push("Signal timestamp is in the future".to_string());
        }
        SignalValidation {
            is_valid: errors.is_empty(),
            errors,
            warnings,
        }
    }
}

pub struct SignalBuilder {
    id: Arc<str>,
    signal_type: SignalType,
    strength: SignalStrength,
    reason: SignalReason,
    price: Option<f64>,
    quantity: Option<f64>,
    timestamp: Option<DateTime<Utc>>,
    metadata: HashMap<String, SignalMetadata>,
}

impl SignalBuilder {
    pub fn new(id: impl Into<Arc<str>>, signal_type: SignalType) -> Self {
        Self {
            id: id.into(),
            signal_type,
            strength: SignalStrength::Medium,
            reason: SignalReason::Custom("Strategy".to_string(), "Default reason".to_string()),
            price: None,
            quantity: None,
            timestamp: None,
            metadata: HashMap::new(),
        }
    }
    pub fn strength(mut self, strength: SignalStrength) -> Self {
        self.strength = strength;
        self
    }
    pub fn reason(mut self, reason: SignalReason) -> Self {
        self.reason = reason;
        self
    }
    pub fn price(mut self, price: f64) -> Self {
        self.price = Some(price);
        self
    }
    pub fn quantity(mut self, quantity: f64) -> Self {
        self.quantity = Some(quantity);
        self
    }
    pub fn timestamp(mut self, timestamp: DateTime<Utc>) -> Self {
        self.timestamp = Some(timestamp);
        self
    }
    pub fn metadata(mut self, key: String, value: SignalMetadata) -> Self {
        self.metadata.insert(key, value);
        self
    }
    pub fn build(self) -> Signal {
        Signal {
            id: self.id,
            timestamp: self.timestamp.unwrap_or_else(Utc::now),
            signal_type: self.signal_type,
            strength: self.strength,
            price: self.price,
            quantity: self.quantity,
            reason: self.reason,
            metadata: self.metadata,
            numeric_metadata: HashMap::new(),
            is_limit: false,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    // ── SignalType ──

    #[test]
    fn signal_type_serde_roundtrip_buy() {
        let st = SignalType::Buy;
        let json = serde_json::to_string(&st).unwrap();
        let st2: SignalType = serde_json::from_str(&json).unwrap();
        assert_eq!(st, st2);
    }

    #[test]
    fn signal_type_serde_two_sided_quote() {
        let st = SignalType::TwoSidedQuote { bid_price: 100.0, ask_price: 101.0, bid_size: 1.0, ask_size: 1.0 };
        let json = serde_json::to_string(&st).unwrap();
        let st2: SignalType = serde_json::from_str(&json).unwrap();
        assert_eq!(st, st2);
    }

    #[test]
    fn signal_type_custom_serde() {
        let st = SignalType::Custom("MySignal".to_string());
        let json = serde_json::to_string(&st).unwrap();
        let st2: SignalType = serde_json::from_str(&json).unwrap();
        assert_eq!(st, st2);
    }

    // ── SignalStrength ──

    #[test]
    fn signal_strength_serde() {
        let strengths = vec![SignalStrength::Weak, SignalStrength::Medium, SignalStrength::Strong, SignalStrength::Custom(0.42)];
        for s in strengths {
            let json = serde_json::to_string(&s).unwrap();
            let s2: SignalStrength = serde_json::from_str(&json).unwrap();
            assert_eq!(s, s2);
        }
    }

    // ── SignalReason ──

    #[test]
    fn signal_reason_description() {
        let r = SignalReason::TechnicalAnalysis("RSI overbought".to_string());
        assert!(r.description().contains("RSI"));
        let r2 = SignalReason::Custom("ML".to_string(), "prediction".to_string());
        assert!(r2.description().contains("ML"));
    }

    // ── SignalMetadata ──

    #[test]
    fn signal_metadata_as_float() {
        assert_eq!(SignalMetadata::Number(42.0).as_float(), Some(42.0));
        assert_eq!(SignalMetadata::Percentage(0.5).as_float(), Some(0.5));
        assert_eq!(SignalMetadata::Boolean(true).as_float(), Some(1.0));
        assert_eq!(SignalMetadata::Price(99.5).as_float(), Some(99.5));
        assert_eq!(SignalMetadata::Text("hello".to_string()).as_float(), None);
    }

    #[test]
    fn signal_metadata_as_string() {
        assert_eq!(SignalMetadata::Number(42.0).as_string(), "42");
        assert_eq!(SignalMetadata::Text("hi".to_string()).as_string(), "hi");
        assert_eq!(SignalMetadata::Boolean(false).as_string(), "false");
        assert!(SignalMetadata::Percentage(0.5).as_string().contains("50.00%"));
    }

    // ── Signal constructors ──

    #[test]
    fn signal_buy_constructor() {
        let s = Signal::buy("test-1", SignalStrength::Strong, SignalReason::Momentum("up".into()));
        assert!(matches!(s.signal_type, SignalType::Buy));
        assert!(s.is_entry_signal());
        assert!(!s.is_exit_signal());
    }

    #[test]
    fn signal_sell_constructor() {
        let s = Signal::sell("test-2", SignalStrength::Medium, SignalReason::Momentum("down".into()));
        assert!(matches!(s.signal_type, SignalType::Sell));
    }

    #[test]
    fn signal_hold() {
        let s = Signal::hold("h1", SignalReason::PriceAction("flat".into()));
        assert!(matches!(s.signal_type, SignalType::Hold));
        assert!(!s.is_entry_signal());
        assert!(!s.is_exit_signal());
    }

    #[test]
    fn signal_close_is_exit() {
        let s = Signal::close("c1", SignalStrength::Strong, SignalReason::RiskManagement("stop".into()));
        assert!(s.is_exit_signal());
    }

    #[test]
    fn signal_two_sided_quote() {
        let s = Signal::two_sided_quote(
            "q1", 100.0, 101.0, 1.0, 1.0,
            SignalStrength::Medium, SignalReason::PriceAction("spread".into()),
        );
        assert!(s.is_entry_signal());
    }

    #[test]
    fn signal_cancel_quotes_is_exit() {
        let s = Signal::cancel_quotes("cq1", SignalReason::RiskManagement("halt".into()));
        assert!(s.is_exit_signal());
    }

    // ── Signal builder methods ──

    #[test]
    fn signal_with_price_and_quantity() {
        let s = Signal::buy("b1", SignalStrength::Strong, SignalReason::Momentum("up".into()))
            .with_price(50000.0)
            .with_quantity(0.1);
        assert_eq!(s.price, Some(50000.0));
        assert_eq!(s.quantity, Some(0.1));
    }

    #[test]
    fn signal_with_metadata() {
        let s = Signal::buy("b2", SignalStrength::Medium, SignalReason::Momentum("test".into()))
            .with_metadata("rsi".to_string(), SignalMetadata::Number(72.0));
        assert_eq!(s.metadata.len(), 1);
    }

    #[test]
    fn signal_with_numeric() {
        let s = Signal::buy("b3", SignalStrength::Weak, SignalReason::Momentum("x".into()))
            .with_numeric("confidence", 0.95);
        assert_eq!(s.numeric_metadata.get("confidence"), Some(&0.95));
    }

    #[test]
    fn signal_with_limit() {
        let s = Signal::buy("b4", SignalStrength::Weak, SignalReason::Momentum("x".into()))
            .with_limit(true);
        assert!(s.is_limit);
    }

    // ── strength_value ──

    #[test]
    fn strength_value_mapping() {
        let s = Signal::buy("sv", SignalStrength::Weak, SignalReason::Momentum("x".into()));
        assert!((s.strength_value() - 0.33).abs() < 1e-10);

        let s2 = Signal::buy("sv2", SignalStrength::Strong, SignalReason::Momentum("x".into()));
        assert!((s2.strength_value() - 1.0).abs() < 1e-10);

        let s3 = Signal::buy("sv3", SignalStrength::Custom(0.5), SignalReason::Momentum("x".into()));
        assert!((s3.strength_value() - 0.5).abs() < 1e-10);
    }

    // ── is_scaling_signal ──

    #[test]
    fn scaling_signal_detection() {
        let s = Signal::new("sc1", SignalType::ScaleIn, SignalStrength::Medium, SignalReason::Momentum("x".into()));
        assert!(s.is_scaling_signal());
        let s2 = Signal::new("sc2", SignalType::ScaleOut, SignalStrength::Medium, SignalReason::Momentum("x".into()));
        assert!(s2.is_scaling_signal());
    }

    // ── validate ──

    #[test]
    fn validate_valid_entry() {
        let s = Signal::buy("v1", SignalStrength::Strong, SignalReason::Momentum("x".into()))
            .with_price(100.0)
            .with_quantity(1.0);
        let v = s.validate();
        assert!(v.is_valid);
        assert!(v.errors.is_empty());
    }

    #[test]
    fn validate_empty_id() {
        let s = Signal::new("", SignalType::Buy, SignalStrength::Strong, SignalReason::Momentum("x".into()));
        let v = s.validate();
        assert!(!v.is_valid);
        assert!(v.errors.iter().any(|e| e.contains("ID")));
    }

    #[test]
    fn validate_negative_price() {
        let s = Signal::buy("v2", SignalStrength::Strong, SignalReason::Momentum("x".into()))
            .with_price(-10.0);
        let v = s.validate();
        assert!(!v.is_valid);
    }

    #[test]
    fn validate_entry_without_price_warns() {
        let s = Signal::buy("v3", SignalStrength::Strong, SignalReason::Momentum("x".into()));
        let v = s.validate();
        assert!(v.is_valid); // warnings don't make it invalid
        assert!(!v.warnings.is_empty());
    }

    #[test]
    fn validate_option_spread_empty_legs() {
        let s = Signal::new("os1", SignalType::OptionSpread { legs: vec![] },
            SignalStrength::Strong, SignalReason::Arbitrage("x".into()));
        let v = s.validate();
        assert!(!v.is_valid);
    }

    // ── SignalBuilder ──

    #[test]
    fn signal_builder_basic() {
        let s = SignalBuilder::new("sb1", SignalType::Buy)
            .strength(SignalStrength::Strong)
            .reason(SignalReason::Momentum("trend".into()))
            .price(100.0)
            .quantity(5.0)
            .build();
        assert_eq!(s.price, Some(100.0));
        assert_eq!(s.quantity, Some(5.0));
        assert!(matches!(s.strength, SignalStrength::Strong));
    }

    #[test]
    fn signal_builder_with_metadata() {
        let s = SignalBuilder::new("sb2", SignalType::Sell)
            .metadata("key".to_string(), SignalMetadata::Boolean(true))
            .build();
        assert!(s.metadata.contains_key("key"));
    }

    // ── Serde roundtrip for Signal ──

    #[test]
    fn signal_serde_roundtrip() {
        let s = Signal::buy("serde1", SignalStrength::Strong, SignalReason::Momentum("up".into()))
            .with_price(50000.0)
            .with_quantity(1.0);
        let json = serde_json::to_string(&s).unwrap();
        let s2: Signal = serde_json::from_str(&json).unwrap();
        assert_eq!(s2.price, Some(50000.0));
        assert!(matches!(s2.signal_type, SignalType::Buy));
    }
}
