[package]
name = "riskmanager"
version = "0.1.0"
edition = "2021"

[features]
default = []
postgres = []

[dependencies]
serde = { version = "1.0", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }
derivatives = { path = "../derivatives" }

# Logging
ultra-logger = { git = "https://github.com/Nwagbara-Group-LLC/LoggingEngine", tag = "v0.1.0" }
once_cell = "1.0"
tokio = { version = "1.0", features = ["full"] }

[dev-dependencies]
serde_json = "1.0"
criterion = "0.5"
rand = "0.8"

[[bench]]
name = "riskmanager_benchmark"
harness = false
