//! Cross-Asset Correlation Monitoring for Portfolio Risk Management
//!
//! Provides real-time monitoring of correlations between assets to:
//! - Detect correlation breakdown/regime changes
//! - Monitor portfolio diversification
//! - Identify hidden risk concentrations
//! - Generate alerts for correlation spikes

use std::collections::{HashMap, VecDeque};
use serde::{Deserialize, Serialize};
use chrono::{DateTime, Utc};

/// Configuration for cross-asset correlation monitoring
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CorrelationMonitorConfig {
    /// Window size for rolling correlation calculation
    pub rolling_window: usize,
    /// Correlation change threshold for breakdown alert
    pub breakdown_threshold: f64,
    /// High correlation threshold (assets considered correlated above this)
    pub high_correlation_threshold: f64,
    /// Extreme correlation threshold (risk alert level)
    pub extreme_correlation_threshold: f64,
    /// Minimum periods required before generating alerts
    pub warmup_periods: usize,
    /// Whether to use exponential weighting (more weight on recent data)
    pub use_exponential_weighting: bool,
    /// Decay factor for exponential weighting (0.9 - 0.99 typical)
    pub exponential_decay: f64,
}

impl Default for CorrelationMonitorConfig {
    fn default() -> Self {
        Self {
            rolling_window: 30,
            breakdown_threshold: 0.3,
            high_correlation_threshold: 0.7,
            extreme_correlation_threshold: 0.9,
            warmup_periods: 20,
            use_exponential_weighting: true,
            exponential_decay: 0.94,
        }
    }
}

/// Alert generated by correlation monitor
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CorrelationAlert {
    /// Alert type
    pub alert_type: CorrelationAlertType,
    /// First asset in the pair
    pub asset_a: String,
    /// Second asset in the pair
    pub asset_b: String,
    /// Previous correlation value
    pub previous_correlation: f64,
    /// Current correlation value
    pub current_correlation: f64,
    /// Absolute change magnitude
    pub change_magnitude: f64,
    /// Timestamp of alert
    pub timestamp: DateTime<Utc>,
    /// Severity level (0.0 - 1.0)
    pub severity: f64,
    /// Human-readable message
    pub message: String,
}

/// Types of correlation alerts
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum CorrelationAlertType {
    /// Correlation increased significantly
    CorrelationSpike,
    /// Correlation decreased significantly (diversification opportunity)
    CorrelationBreakdown,
    /// Correlation exceeded high threshold
    HighCorrelation,
    /// Correlation exceeded extreme threshold
    ExtremeCorrelation,
    /// Correlation flipped sign (e.g., from positive to negative)
    SignFlip,
    /// Overall portfolio correlation is increasing
    PortfolioConcentration,
}

/// Summary of portfolio correlation state
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct PortfolioCorrelationSummary {
    /// Average pairwise correlation
    pub average_correlation: f64,
    /// Maximum pairwise correlation
    pub max_correlation: f64,
    /// Minimum pairwise correlation (most negative)
    pub min_correlation: f64,
    /// Number of highly correlated pairs
    pub high_correlation_pairs: usize,
    /// Number of extreme correlation pairs
    pub extreme_correlation_pairs: usize,
    /// Effective number of independent assets (diversification measure)
    pub effective_assets: f64,
    /// Portfolio concentration risk score (0-1)
    pub concentration_risk: f64,
    /// Timestamp
    pub timestamp: DateTime<Utc>,
}

/// Cross-asset correlation monitor
pub struct CrossAssetCorrelationMonitor {
    config: CorrelationMonitorConfig,
    /// Rolling returns for each asset
    returns: HashMap<String, VecDeque<f64>>,
    /// Cached correlation matrix
    correlations: HashMap<(String, String), f64>,
    /// Historical correlations for breakdown detection
    historical_correlations: HashMap<(String, String), VecDeque<f64>>,
    /// Current update count
    update_count: usize,
    /// Last summary
    last_summary: Option<PortfolioCorrelationSummary>,
}

impl CrossAssetCorrelationMonitor {
    pub fn new(config: CorrelationMonitorConfig) -> Self {
        Self {
            config,
            returns: HashMap::new(),
            correlations: HashMap::new(),
            historical_correlations: HashMap::new(),
            update_count: 0,
            last_summary: None,
        }
    }
    
    /// Add a return observation for an asset
    pub fn add_return(&mut self, asset: &str, return_value: f64) {
        let returns = self.returns.entry(asset.to_string())
            .or_insert_with(|| VecDeque::with_capacity(self.config.rolling_window + 1));
        
        returns.push_back(return_value);
        
        // Keep only rolling_window returns
        while returns.len() > self.config.rolling_window {
            returns.pop_front();
        }
    }
    
    /// Update all correlations and return any alerts
    pub fn update(&mut self) -> Vec<CorrelationAlert> {
        self.update_count += 1;
        
        let assets: Vec<String> = self.returns.keys().cloned().collect();
        let mut alerts = Vec::new();
        
        if assets.len() < 2 {
            return alerts;
        }
        
        // Calculate all pairwise correlations
        for i in 0..assets.len() {
            for j in (i + 1)..assets.len() {
                let asset_a = &assets[i];
                let asset_b = &assets[j];
                
                if let Some(new_corr) = self.calculate_correlation(asset_a, asset_b) {
                    let key = self.make_key(asset_a, asset_b);
                    let old_corr = self.correlations.get(&key).copied();
                    
                    // Store new correlation
                    self.correlations.insert(key.clone(), new_corr);
                    
                    // Track historical
                    let history = self.historical_correlations.entry(key.clone())
                        .or_insert_with(VecDeque::new);
                    history.push_back(new_corr);
                    while history.len() > self.config.rolling_window {
                        history.pop_front();
                    }
                    
                    // Check for alerts (after warmup)
                    if self.update_count >= self.config.warmup_periods {
                        if let Some(alert) = self.check_for_alerts(
                            asset_a, asset_b, old_corr, new_corr
                        ) {
                            alerts.push(alert);
                        }
                    }
                }
            }
        }
        
        // Update summary
        self.last_summary = Some(self.calculate_summary());
        
        // Check for portfolio-level alerts
        if let Some(ref summary) = self.last_summary {
            if summary.concentration_risk > 0.8 {
                alerts.push(CorrelationAlert {
                    alert_type: CorrelationAlertType::PortfolioConcentration,
                    asset_a: "PORTFOLIO".to_string(),
                    asset_b: "PORTFOLIO".to_string(),
                    previous_correlation: 0.0,
                    current_correlation: summary.average_correlation,
                    change_magnitude: summary.concentration_risk,
                    timestamp: Utc::now(),
                    severity: summary.concentration_risk,
                    message: format!(
                        "Portfolio concentration risk: {:.1}% - average correlation {:.2}",
                        summary.concentration_risk * 100.0,
                        summary.average_correlation
                    ),
                });
            }
        }
        
        alerts
    }
    
    /// Calculate correlation between two assets
    fn calculate_correlation(&self, asset_a: &str, asset_b: &str) -> Option<f64> {
        let returns_a = self.returns.get(asset_a)?;
        let returns_b = self.returns.get(asset_b)?;
        
        let min_len = returns_a.len().min(returns_b.len());
        if min_len < 10 {
            return None;
        }
        
        // Get vectors
        let a: Vec<f64> = returns_a.iter().rev().take(min_len).copied().collect();
        let b: Vec<f64> = returns_b.iter().rev().take(min_len).copied().collect();
        
        if self.config.use_exponential_weighting {
            self.exponentially_weighted_correlation(&a, &b)
        } else {
            pearson_correlation(&a, &b)
        }
    }
    
    /// Calculate exponentially weighted correlation
    fn exponentially_weighted_correlation(&self, x: &[f64], y: &[f64]) -> Option<f64> {
        let n = x.len();
        if n < 2 || y.len() != n {
            return None;
        }
        
        // Calculate weights (most recent gets highest weight)
        let mut weights: Vec<f64> = Vec::with_capacity(n);
        let mut weight = 1.0;
        for _ in 0..n {
            weights.push(weight);
            weight *= self.config.exponential_decay;
        }
        
        let weight_sum: f64 = weights.iter().sum();
        
        // Weighted means
        let mean_x: f64 = x.iter().zip(&weights).map(|(xi, w)| xi * w).sum::<f64>() / weight_sum;
        let mean_y: f64 = y.iter().zip(&weights).map(|(yi, w)| yi * w).sum::<f64>() / weight_sum;
        
        // Weighted covariance and variances
        let mut cov = 0.0;
        let mut var_x = 0.0;
        let mut var_y = 0.0;
        
        for i in 0..n {
            let dx = x[i] - mean_x;
            let dy = y[i] - mean_y;
            cov += weights[i] * dx * dy;
            var_x += weights[i] * dx * dx;
            var_y += weights[i] * dy * dy;
        }
        
        let denom = (var_x * var_y).sqrt();
        if denom < f64::EPSILON {
            return None;
        }
        
        Some(cov / denom)
    }
    
    /// Check for correlation alerts
    fn check_for_alerts(
        &self,
        asset_a: &str,
        asset_b: &str,
        old_corr: Option<f64>,
        new_corr: f64,
    ) -> Option<CorrelationAlert> {
        let timestamp = Utc::now();
        
        // Check for extreme correlation
        if new_corr.abs() >= self.config.extreme_correlation_threshold {
            return Some(CorrelationAlert {
                alert_type: CorrelationAlertType::ExtremeCorrelation,
                asset_a: asset_a.to_string(),
                asset_b: asset_b.to_string(),
                previous_correlation: old_corr.unwrap_or(0.0),
                current_correlation: new_corr,
                change_magnitude: new_corr.abs(),
                timestamp,
                severity: 0.9,
                message: format!(
                    "Extreme correlation {:.2} between {} and {}",
                    new_corr, asset_a, asset_b
                ),
            });
        }
        
        // Check for high correlation
        if new_corr.abs() >= self.config.high_correlation_threshold 
            && old_corr.map(|o| o.abs() < self.config.high_correlation_threshold).unwrap_or(true) 
        {
            return Some(CorrelationAlert {
                alert_type: CorrelationAlertType::HighCorrelation,
                asset_a: asset_a.to_string(),
                asset_b: asset_b.to_string(),
                previous_correlation: old_corr.unwrap_or(0.0),
                current_correlation: new_corr,
                change_magnitude: new_corr.abs(),
                timestamp,
                severity: 0.6,
                message: format!(
                    "High correlation {:.2} between {} and {}",
                    new_corr, asset_a, asset_b
                ),
            });
        }
        
        // Check for significant change (breakdown or spike)
        if let Some(old) = old_corr {
            let change = (new_corr - old).abs();
            
            if change >= self.config.breakdown_threshold {
                let alert_type = if new_corr.abs() > old.abs() {
                    CorrelationAlertType::CorrelationSpike
                } else {
                    CorrelationAlertType::CorrelationBreakdown
                };
                
                return Some(CorrelationAlert {
                    alert_type,
                    asset_a: asset_a.to_string(),
                    asset_b: asset_b.to_string(),
                    previous_correlation: old,
                    current_correlation: new_corr,
                    change_magnitude: change,
                    timestamp,
                    severity: (change / self.config.breakdown_threshold).min(1.0) * 0.7,
                    message: format!(
                        "Correlation {} from {:.2} to {:.2} between {} and {}",
                        if new_corr.abs() > old.abs() { "spiked" } else { "broke down" },
                        old, new_corr, asset_a, asset_b
                    ),
                });
            }
            
            // Check for sign flip
            if old * new_corr < 0.0 && old.abs() > 0.1 && new_corr.abs() > 0.1 {
                return Some(CorrelationAlert {
                    alert_type: CorrelationAlertType::SignFlip,
                    asset_a: asset_a.to_string(),
                    asset_b: asset_b.to_string(),
                    previous_correlation: old,
                    current_correlation: new_corr,
                    change_magnitude: (new_corr - old).abs(),
                    timestamp,
                    severity: 0.8,
                    message: format!(
                        "Correlation sign flip from {:.2} to {:.2} between {} and {}",
                        old, new_corr, asset_a, asset_b
                    ),
                });
            }
        }
        
        None
    }
    
    /// Calculate portfolio correlation summary
    fn calculate_summary(&self) -> PortfolioCorrelationSummary {
        if self.correlations.is_empty() {
            return PortfolioCorrelationSummary {
                timestamp: Utc::now(),
                ..Default::default()
            };
        }
        
        let correlations: Vec<f64> = self.correlations.values().copied().collect();
        let n = correlations.len();
        
        let average = correlations.iter().sum::<f64>() / n as f64;
        let max = correlations.iter().copied().fold(f64::NEG_INFINITY, f64::max);
        let min = correlations.iter().copied().fold(f64::INFINITY, f64::min);
        
        let high_pairs = correlations.iter()
            .filter(|&&c| c.abs() >= self.config.high_correlation_threshold)
            .count();
        let extreme_pairs = correlations.iter()
            .filter(|&&c| c.abs() >= self.config.extreme_correlation_threshold)
            .count();
        
        // Effective number of assets: N / (1 + (N-1) * avg_correlation)
        let num_assets = self.returns.len();
        let effective = if average.abs() < 1.0 {
            num_assets as f64 / (1.0 + (num_assets as f64 - 1.0) * average.abs())
        } else {
            1.0
        };
        
        // Concentration risk: higher when correlations are high and extreme pairs exist
        let concentration = (average.abs() * 0.5 
            + (high_pairs as f64 / n.max(1) as f64) * 0.3
            + (extreme_pairs as f64 / n.max(1) as f64) * 0.2)
            .min(1.0);
        
        PortfolioCorrelationSummary {
            average_correlation: average,
            max_correlation: max,
            min_correlation: min,
            high_correlation_pairs: high_pairs,
            extreme_correlation_pairs: extreme_pairs,
            effective_assets: effective,
            concentration_risk: concentration,
            timestamp: Utc::now(),
        }
    }
    
    /// Make consistent key for correlation pair
    fn make_key(&self, a: &str, b: &str) -> (String, String) {
        if a < b {
            (a.to_string(), b.to_string())
        } else {
            (b.to_string(), a.to_string())
        }
    }
    
    /// Get current correlation between two assets
    pub fn get_correlation(&self, asset_a: &str, asset_b: &str) -> Option<f64> {
        let key = self.make_key(asset_a, asset_b);
        self.correlations.get(&key).copied()
    }
    
    /// Get correlation matrix as vectors
    pub fn get_correlation_matrix(&self) -> (Vec<String>, Vec<Vec<f64>>) {
        let assets: Vec<String> = self.returns.keys().cloned().collect();
        let n = assets.len();
        let mut matrix = vec![vec![0.0; n]; n];
        
        for i in 0..n {
            matrix[i][i] = 1.0;
            for j in (i + 1)..n {
                let corr = self.get_correlation(&assets[i], &assets[j]).unwrap_or(0.0);
                matrix[i][j] = corr;
                matrix[j][i] = corr;
            }
        }
        
        (assets, matrix)
    }
    
    /// Get current portfolio summary
    pub fn get_summary(&self) -> Option<&PortfolioCorrelationSummary> {
        self.last_summary.as_ref()
    }
    
    /// Clear all data
    pub fn reset(&mut self) {
        self.returns.clear();
        self.correlations.clear();
        self.historical_correlations.clear();
        self.update_count = 0;
        self.last_summary = None;
    }
}

/// Pearson correlation coefficient
fn pearson_correlation(x: &[f64], y: &[f64]) -> Option<f64> {
    if x.len() != y.len() || x.len() < 2 {
        return None;
    }
    
    let n = x.len() as f64;
    let mean_x: f64 = x.iter().sum::<f64>() / n;
    let mean_y: f64 = y.iter().sum::<f64>() / n;
    
    let mut cov = 0.0;
    let mut var_x = 0.0;
    let mut var_y = 0.0;
    
    for i in 0..x.len() {
        let dx = x[i] - mean_x;
        let dy = y[i] - mean_y;
        cov += dx * dy;
        var_x += dx * dx;
        var_y += dy * dy;
    }
    
    let denom = (var_x * var_y).sqrt();
    if denom < f64::EPSILON {
        return None;
    }
    
    Some(cov / denom)
}

#[cfg(test)]
mod tests {
    use super::*;
    
    #[test]
    fn test_correlation_monitoring() {
        let config = CorrelationMonitorConfig::default();
        let mut monitor = CrossAssetCorrelationMonitor::new(config);
        
        // Add correlated returns
        for i in 0..30 {
            let base = (i as f64 * 0.1).sin();
            monitor.add_return("BTC", base + 0.01);
            monitor.add_return("ETH", base * 0.8 + 0.005); // Positively correlated
            monitor.add_return("GOLD", -base * 0.5 + 0.002); // Negatively correlated
        }
        
        let _alerts = monitor.update();
        
        // Check correlations
        let btc_eth = monitor.get_correlation("BTC", "ETH").unwrap();
        let btc_gold = monitor.get_correlation("BTC", "GOLD").unwrap();
        
        assert!(btc_eth > 0.5, "BTC-ETH should be positively correlated: {}", btc_eth);
        assert!(btc_gold < 0.0, "BTC-GOLD should be negatively correlated: {}", btc_gold);
        
        // Check summary
        let summary = monitor.get_summary().unwrap();
        assert!(summary.average_correlation.abs() > 0.0);
    }
    
    #[test]
    fn test_correlation_alerts() {
        let config = CorrelationMonitorConfig {
            warmup_periods: 5,
            rolling_window: 10,
            ..Default::default()
        };
        let mut monitor = CrossAssetCorrelationMonitor::new(config);
        
        // Warmup with low correlation
        for _ in 0..10 {
            monitor.add_return("A", rand::random::<f64>() - 0.5);
            monitor.add_return("B", rand::random::<f64>() - 0.5);
            monitor.update();
        }
        
        // Switch to high correlation
        for i in 0..10 {
            let base = i as f64 * 0.1;
            monitor.add_return("A", base);
            monitor.add_return("B", base * 0.95);
        }
        
        let alerts = monitor.update();
        
        // Should get high correlation or spike alert
        let has_correlation_alert = alerts.iter().any(|a| {
            matches!(a.alert_type, 
                CorrelationAlertType::HighCorrelation 
                | CorrelationAlertType::CorrelationSpike
                | CorrelationAlertType::ExtremeCorrelation
            )
        });
        
        assert!(has_correlation_alert || alerts.is_empty(), "Should detect correlation change or have no alerts");
    }
    
    #[test]
    fn test_portfolio_summary() {
        let config = CorrelationMonitorConfig::default();
        let mut monitor = CrossAssetCorrelationMonitor::new(config);
        
        // Add multiple assets with varying correlations
        for i in 0..30 {
            let t = i as f64 * 0.1;
            monitor.add_return("A", t.sin());
            monitor.add_return("B", t.sin() * 0.9);
            monitor.add_return("C", t.cos());
            monitor.add_return("D", (t * 2.0).sin());
        }
        
        monitor.update();
        
        let summary = monitor.get_summary().unwrap();
        
        // Should have valid summary
        assert!(summary.effective_assets >= 1.0);
        assert!(summary.concentration_risk >= 0.0 && summary.concentration_risk <= 1.0);
    }
}
